In [74]:
import pandas as pd

df = pd.read_csv(
    r"C:\\Users\\KIIT0001\\Desktop\\Scouting_System Project\\data\\processed\\players_data-2025_2026.csv"
)

In [75]:
POSITION_FEATURES = {

    "GK": {
        "primary": [
            "Saves",
            "Save%",
            "CS"
        ],
        "secondary": [
            "Touches",
            "Carries"
        ]
    },

    "DF": {
        "primary": [
            "Tkl",
            "Int",
            "Blocks",
            "Clr"
        ],
        "secondary": [
            "PrgP",
            "Touches"
        ]
    },

    "MF": {
        "primary": [
            "PrgP",
            "KP",
            "Touches",
            "Carries"
        ],
        "secondary": [
            "Tkl",
            "Recov",
            "Ast"
        ]
    },

    "FW": {
        "primary": [
            "Gls",
            "xG",
            "G+A"
        ],
        "secondary": [
            "Ast",
            "KP",
            "PrgR"
        ]
    }
}

In [76]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [77]:
def get_similar_players(
    player_name,
    position,
    top_n=10
):

    features = get_position_features(position)

    position_df = df[
        df["Pos"].str.contains(position, na=False)
    ].copy()

    similarity_matrix = cosine_similarity(
        position_df[features]
    )

    player_index = position_df[
        position_df["Player"] == player_name
    ].index[0]

    player_row = position_df.index.get_loc(
        player_index
    )

    scores = list(
        enumerate(
            similarity_matrix[player_row]
        )
    )

    scores = sorted(
        scores,
        key=lambda x: x[1],
        reverse=True
    )

    recommendations = []

    for idx, score in scores[1:top_n+1]:

        recommendations.append({

            "Player":
            position_df.iloc[idx]["Player"],

            "Similarity":
            round(score * 100, 2)

        })

    return pd.DataFrame(
        recommendations
    )

In [78]:
mf_df = df[
    df["Pos"].str.contains(
        "MF",
        na=False
    )
]

print(len(mf_df))

1539

In [79]:
get_similar_players(
    player_name="Declan Rice",
    position="MF"
)

             Player  Similarity
0   Saud Abdulhamid       100.0
1    Matthis Abline       100.0
2             Abner       100.0
3       Tyler Adams       100.0
4     Karim Adeyemi       100.0
5     Simon Adingra       100.0
6        Amine Adli       100.0
7  Michel Aebischer       100.0
8     Lucien Agoume       100.0
9       Marc Aguado       100.0

In [80]:
from sklearn.cluster import KMeans

In [81]:
mf_df = df[
    df["Pos"].str.contains(
        "MF",
        na=False
    )
].copy()

In [82]:
features = [
    col for col in POSITION_FEATURES["MF"]["primary"]
    + POSITION_FEATURES["MF"]["secondary"]
    if col in mf_df.columns
]

In [83]:
kmeans = KMeans(
    n_clusters=5,
    random_state=42
)

mf_df["Cluster"] = kmeans.fit_predict(
    mf_df[features]
)

In [84]:
mf_df[
    ["Player","Cluster"]
].head(20)

                 Player  Cluster
0      Brenden Aaronson        2
1          Jerome Abbey        1
3   Jones El-Abdellaoui        1
4         Himad Abdelli        1
5         Himad Abdelli        1
6              Ali Abdi        1
7     Salis Abdul Samed        1
8       Saud Abdulhamid        0
9              Tay Abed        1
10      Laurent Abergel        1
11       Matthis Abline        0
12                Abner        0
13    Zakaria Aboukhlal        1
16          Francis Abu        1
17    Giorgi Abuashvili        1
18    Mathieu Acapandié        1
24          Tyler Adams        0
27         Jayden Addai        1
28        Karim Adeyemi        0
29        Simon Adingra        1

In [87]:
print(features)

['Ast']

In [86]:
for col in df.columns:
    print(col)

Rk
Player
Nation
Pos
Squad
Comp
Age
Born
MP
Starts
Min
90s
Gls
Ast
G+A
G-PK
PK
PKatt
CrdY
CrdR
G+A-PK
Rk_stats_keeper
Nation_stats_keeper
Pos_stats_keeper
Comp_stats_keeper
Age_stats_keeper
Born_stats_keeper
MP_stats_keeper
Starts_stats_keeper
Min_stats_keeper
90s_stats_keeper
GA
GA90
SoTA
Saves
Save%
W
D
L
CS
CS%
PKatt_stats_keeper
PKA
PKsv
PKm
Rk_stats_shooting
Nation_stats_shooting
Pos_stats_shooting
Comp_stats_shooting
Age_stats_shooting
Born_stats_shooting
90s_stats_shooting
Gls_stats_shooting
Sh
SoT
SoT%
Sh/90
SoT/90
G/Sh
G/SoT
PK_stats_shooting
PKatt_stats_shooting
Rk_stats_playing_time
Nation_stats_playing_time
Pos_stats_playing_time
Comp_stats_playing_time
Age_stats_playing_time
Born_stats_playing_time
MP_stats_playing_time
Min_stats_playing_time
Mn/MP
Min%
90s_stats_playing_time
Starts_stats_playing_time
Mn/Start
Compl
Subs
Mn/Sub
unSub
PPM
onG
onGA
+/-
+/-90
On-Off
Rk_stats_misc
Nation_stats_misc
Pos_stats_misc
Comp_stats_misc
Age_stats_misc
Born_stats_misc
90s_stats_misc
CrdY_stats_misc
CrdR_stats_misc
2CrdY
Fls
Fld
Off
Crs
Int
TklW
OG